### ISSUE TITLE
Cloud Robotics Core is failing on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [googlecloudrobotics/core#13]
Due to https://github.com/bazelbuild/continuous-integration/issues/799

Please update your dependency on https://github.com/apcera/libretto since it's now private or deleted.

**Comment by meteorcloudy** [comment]
I'll disable Cloud Robotics Core in Bazel's downstream pipeline, please ping me to re-enable it once this issue is fixed.

**Comment by drigz** [comment]
Working on a CL, just waiting for presubmits right now.

**Comment by meteorcloudy** [comment]
Thanks!
