### ISSUE TITLE
when try to ingress de secret token in robot,  It get the following error:  "error from server (NotFound): secrets "robot-master-tls" not found"

### ISSUE THREAD

**Issue by brando14** [googlecloudrobotics/core#18]
![image](https://user-images.githubusercontent.com/46904374/67682478-d742c080-f965-11e9-9002-3332f6554e43.png)

when try to ingress de secret token in robot,  It get the following error:

any idea?

**Comment by drigz** [comment]
`i/o timeout` suggests a transient error (for example, we see it a lot when GKE is updating the cluster). Have you tried multiple times?

If it fails consistently, it suggests something has gone wrong with the cloud deployment. Did you get any errors from `run-install.sh`? Does re-running `bash ./run-install.sh $PROJECT_ID` help? If not, do you see any errors at https://console.cloud.google.com/net-services/loadbalancing/loadBalancers/list or https://console.cloud.google.com/kubernetes/discovery?

**Comment by brando14** [comment]
the error is when a try to connect the robot with gpc, using the
secret token next to i have run the script inside the robot.

**Comment by drigz** [comment]
It is probably failing because something went wrong in an earlier step. Did you follow the [Quickstart](https://googlecloudrobotics.github.io/core/quickstart.html) instructions?

**Comment by brando14** [comment]
thanks i follow the quickstart again

**Comment by ensonic** [comment]
Hi, 
that part is normal. the pod `setup-robot` is a run-once job, that installs the local services and connects the robot-cluster to the cloud. When it is done, it gets deleted since it is not needed anymore.

**Comment by drigz** [comment]
Great, glad to hear rerunning the Quickstart worked. If you run into any other problems, just open an issue!

**Comment by brando14** [comment]
thanks for help :)
