### ISSUE TITLE
Fixes for future Bazel changes

### ISSUE THREAD

**Issue by laurentlb** [googlecloudrobotics/core#2]
Based on our CI tests (https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/95), it looks like the project fails with the following flags:

* `--incompatible_new_actions_api`
* `--incompatible_bzl_disallow_load_after_statement`
* `--incompatible_no_support_tools_in_action_inputs`
* `--incompatible_merge_genfiles_directory`
* `--incompatible_disable_deprecated_attr_params`
* `--incompatible_no_transitive_loads`

Let me know if you need help with this. The error messages should provide enough information (otherwise, check Bazel issue tracker on GitHub for extra information).

**Comment by ensonic** [comment]
Thanks for the heads up - We seems to be hitting this one:
https://github.com/bazelbuild/bazel/issues/7347
```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --verbose_failures --keep_going --jobs=32 --announce_rc --experimental_multi_threaded_digest --sandbox_tmpfs_path=/tmp --remote_timeout=60 --disk_cache= --remote_max_connections=200 --host_platform_remote_properties_override=properties:{name:"platform" value:"ubuntu1804"} --google_default_credentials --remote_http_cache=https://storage.googleapis.com/bazel-untrusted-buildkite-cache --incompatible_new_actions_api incompatible_bzl_disallow_load_after_statement --incompatible_no_support_tools_in_action_inputs --incompatible_disallow_filetype --incompatible_merge_genfiles_directory --incompatible_no_transitive_loads --incompatible_disable_deprecated_attr_params --incompatible_disallow_load_labels_to_cross_package_boundaries --incompatible_disallow_dict_plus --incompatible_disallow_struct_provider_syntax --incompatible_disallow_old_style_args_add //...
--
  | ERROR: Unrecognized option: --incompatible_disallow_struct_provider_syntax
  | INFO: Invocation ID: 9abf76f6-fde8-4128-a8e3-c99c2a5365f9
```
but there is no context in the error message due to which rule this is.

**Comment by laurentlb** [comment]
Sorry, I thought I replied to this earlier.
You can skip `incompatible_disallow_struct_provider_syntax` (your Bazel version doesn't support it, it was added very recently).

Other flags should give you clearer error messages.

**Comment by ensonic** [comment]
Here is the latest
https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/109#685ded1f-9015-4616-8fb8-91a2826ac101
its still failing even though we e.g. just updated rules_docker. We'll keep trying on low prio.

**Comment by drigz** [comment]
A lot of our problems come from grpc/grpc-java, which doesn't appear to be on the Bazel CI, and protobuf, which should be better when 3.7.0 is released. In the long run, we should push for grpc-java to be added to the Bazel CI so they get notified directly.

**Comment by laurentlb** [comment]
Yes, some problems are caused by grpc-java (https://github.com/grpc/grpc-java/issues/5383).
