### ISSUE TITLE
Cloud Robotics Core is incompatible with --incompatible_load_proto_rules_from_bzl

### ISSUE THREAD

**Issue by Yannic** [googlecloudrobotics/core#24]
Hello maintainers of Cloud Robotics Core 👋,

The Bazel team is in progress of migrating the native Protobuf rules to Starlark. As a first step towards this goal, starting with Bazel 3.0, all Protobuf rules will require explicit load statements.

You can use the following [buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier) command to apply most of the required migrations for you:
```shell
buildifier --lint=fix --warnings=native-proto $(find . -name "BUILD" -o -name "BUILD.bazel" -o -name "*.bzl")
```

For further information, see https://github.com/bazelbuild/bazel/issues/8922 or ping me.

Thanks,
Yannic

**Comment by drigz** [comment]
@Yannic, we depend on rules_go, which doesn't appear to have updated: https://github.com/bazelbuild/rules_go/issues/2266

If I understand correctly, it's impossible for us to be compliant until there is a compliant rules_go update available. Let me know if I'm mistaken.

**Comment by Yannic** [comment]
Yes, all (transitive) dependencies also need to become compliant for this repo to become fully compliant.
I submitted a patch to https://github.com/bazelbuild/bazel-gazelle/pull/683 today, which makes `go_repository` compliant. When that PR is merged, I'll look into finishing https://github.com/bazelbuild/rules_go/pull/2315.
