### ISSUE TITLE
No valid versions with the prefix "1.24" found

### ISSUE THREAD

**Issue by tiesus** [googlecloudrobotics/core#316]
Same problem like #86 

Getting the same error, but with version 1.24. I follow this guide https://googlecloudrobotics.github.io/core/how-to/deploy-from-sources . Error occurs during step 5

Deploy the cloud project.

 `./deploy.sh create [PROJECT_ID]`

Error message

Error: googleapi: Error 400: No valid versions with the prefix "1.24" found.
Details:
[
{
"@type": "type.googleapis.com/google.rpc.RequestInfo",
"requestId": "0x7b7d9ce2fd782a6d"
}
]
, badRequest

on cluster.tf line 11, in resource "google_container_cluster" "cloud-robotics":
11: resource "google_container_cluster" "cloud-robotics" {

terraform apply failed

**Comment by tiesus** [comment]
Tested with #317 . This resolves my issue.

**Comment by drigz** [comment]
Thanks for the feedback!
