### ISSUE TITLE
ERROR: Failed to load Starlark extension '@@llvm_toolchain//:toolchains.bzl'. in CI at Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [googlecloudrobotics/core#336]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3660#018db012-ef59-4353-8ce7-f1c8864e4398

 Platform: Ubuntu

 Logs: 
```
ERROR: Failed to load Starlark extension '@@llvm_toolchain//:toolchains.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @@llvm_toolchain
 - @@llvm_toolchain_llvm
This could either mean you have to add the '@@llvm_toolchain_llvm' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
(04:02:39) INFO: Repository llvm_toolchain instantiated at:
  /var/lib/buildkite-agent/builds/bk-docker-rp17/bazel-org-repo-root/core/WORKSPACE:46:15: in <toplevel>
  /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ee5637b7b4bf3d4f87dda1c28f44d63f/external/toolchains_llvm/toolchain/rules.bzl:60:14: in llvm_toolchain
Repository rule toolchain defined at:
  /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ee5637b7b4bf3d4f87dda1c28f44d63f/external/toolchains_llvm/toolchain/rules.bzl:33:28: in <toplevel>
(04:02:39) ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/googlecloudrobotics/core
git reset 265e6b5a878255e7c5b5a389e26ec018a9338921  --hard
export USE_BAZEL_VERSION=76b9ee7317f5537ca74a1313a4af4bba783a46e2
bazel build //... 
 ``` 
 CC Greenteam @mai93

**Comment by ensonic** [comment]
I can't repro it. fro me it builds: https://source.cloud.google.com/results/invocations/5664ead2-7627-45bb-81ad-7e8ac74482e1

**Comment by ensonic** [comment]
there is not `llvm_toolchain_llvm` in the WORKSPACE, really strange. It also builds fine on our CI

https://github.com/googlecloudrobotics/core/actions/runs/8014522913/job/21893260269

Is the buildkite instance testing some deprecation?

**Comment by faximan** [comment]
I'll check a little later but the fix here might be a matter of adding
```
common enable_bzlmod=false
```

to https://github.com/googlecloudrobotics/core/blob/main/.bazelrc.

**Comment by faximan** [comment]
Now I'm confused. I managed to somehow reproduce this using the Bazel commit sha in the original report, but then it went away, and I failed to find a specific set of flags that deterministically triggers the problem. In general, this repo seems to work with --enable_bzlmod on my machine.

**Comment by sgowroji** [comment]
@faximan Now the CI is Green [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-5357-4528-af44-707bdcb4a120](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-5357-4528-af44-707bdcb4a120). Thanks!

**Comment by faximan** [comment]
OK, hmm, none the wiser I guess, but if all good on your side then we can close as this repo is not officially supporting Bazel 7 anyways.

https://github.com/googlecloudrobotics/core/blob/main/.bazelversion
