### ISSUE TITLE
[Bazel CI] No repository visible as '@io_bazel_rules_go' from main repository.


### ISSUE THREAD

**Issue by sgowroji** [googlecloudrobotics/core#413]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4089#0191a183-1973-49a6-b05e-ff44438d7161

 Platform: Ubuntu

 Logs: 
```
ERROR: [0mSkipping '//...': error loading package under directory '': error loading package 'src/go/cmd/token-vendor/api': Unable to find package for @@[unknown repo 'io_bazel_rules_go' requested from @@]//go:def.bzl: The repository '@@[unknown repo 'io_bazel_rules_go' requested from @@]' could not be resolved: No repository visible as '@io_bazel_rules_go' from main repository.
ERROR: [0merror loading package under directory '': error loading package 'src/go/cmd/token-vendor/api': Unable to find package for @@[unknown repo 'io_bazel_rules_go' requested from @@]//go:def.bzl: The repository '@@[unknown repo 'io_bazel_rules_go' requested from @@]' could not be resolved: No repository visible as '@io_bazel_rules_go' from main repository.

``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/5881c38c54416add9faec35b7731954f4baf12d8

 Steps:
  ``` 
 git clone https://github.com/googlecloudrobotics/core
git reset 5929ab84000fb3c5d3e159686e2dafa4d6f02836  --hard
export USE_BAZEL_VERSION=ed8ed01cf3c86485dbd1d756b6e891daad892358
bazel build //... 
 ``` 
 CC Greenteam @mai93

**Comment by ensonic** [comment]
I've only found "https://github.com/bazelbuild/rules_docker/issues/1246" but it looks like a bazel regression for those not yet having converted to bazelmod, right? Somehow the rules eval has changed.

**Comment by mai93** [comment]
based on the culprit (https://github.com/bazelbuild/bazel/commit/5881c38c54416add9faec35b7731954f4baf12d8) in the issue description, you may need to add `--enable_workspace` explicitly as it is flipped to false in bazel @head

**Comment by Wyverald** [comment]
This can be closed now -- the commit above makes Bazel CI specify the `--enable_workspace` flag when running from Bazel@HEAD.

**Comment by ensonic** [comment]
Thanks! We'll try to migrate to modules.
