### ISSUE TITLE
Container registry API is not enabled by deploy.sh script

### ISSUE THREAD

**Issue by oliver-goetz** [googlecloudrobotics/core#44]
When you deploy Cloud Robotics in a fresh GCP project it `deploy.sh create [project-name]` fails in default settings with this error message because it does not enable GCP container registry API
```
F0512 07:24:16.916115   35662 fast_pusher_.py:194] Error publishing gcr.io/[project-name]/setup-robot:latest: Bad status during token exchange: 403
{"errors":[{"code":"DENIED","message":"Token exchange failed for project '[project-name]'. Please enable Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=[project-name] before performing this operation."}]}
----------------
Note: The failure of target @containerregistry//:pusher (with exit code 1) may have been caused by the fact that it is running under Python 2 instead of Python 3. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY3, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.

```

**Comment by drigz** [comment]
It should be enabled by Terraform: https://github.com/googlecloudrobotics/core/blob/2cd7a4fa5f5b80ca3d07d11f66da32a83cea461c/src/bootstrap/cloud/terraform/project.tf#L55

Maybe this is a race condition or an ordering issue? Does it work if you rerun or do you have to enable at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?

**Comment by oliver-goetz** [comment]
It only works when I enable the api manually.
Terraform is running after `prepare_source_install` function, where the first images are pushed. Probably that's where it fails.

https://github.com/googlecloudrobotics/core/blob/2cd7a4fa5f5b80ca3d07d11f66da32a83cea461c/deploy.sh#L310-L317

**Comment by drigz** [comment]
I was very confused by this as I somehow remembered fixing it in the past. It turns out I never sent that change for review 🙈  Sorry this bit you!

**Comment by oliver-goetz** [comment]
Thanks for fixing this. It was no big issue, but is looking cleaner now
