### ISSUE TITLE
cr-syncer doesn't work if robot name is longer than 22 characters

### ISSUE THREAD

**Issue by drigz** [googlecloudrobotics/core#46]
The cr-syncer adds a finalizer with the name `robot-<robot-name>.synced.cr-syncer.cloudrobotics.com.
If you create a robot name longer than 22 characters, the finalizer name is too long and the cr-syncer encounters the error `name part must be no more than 63 characters`.

I can imagine solving this by truncating the robot name and adding an alphanumeric hash; we'd have to ensure old finalizers are removed in the migration.

**Comment by oliver-goetz** [comment]
Is there a requirement of having robot names longer than 22 characters? 
If not we could limit the length of robot names with a webhook in cloud-master, robot-master and additionally in the robot deployment tool.
This is much easier to read than alphanumeric hashs.

**Comment by drigz** [comment]
This is obsolete now that the cr-syncer no longer adds finalizers.
