### ISSUE TITLE
Offline robot clusters block deployment of recreated approllouts

### ISSUE THREAD

**Issue by oliver-goetz** [googlecloudrobotics/core#47]
Offline robot clusters can block approllouts recreated with the same name.
These are the steps to reproduce the error:

1. Setup a scenario with multiple robot clusters
2. Create an approllout which affects all clusters and wait until it is successfully deployed on all robots
3. Turn off one robot cluster (or cut its connection to cloud cluster)
4. Delete the approllout
5. Create the same approllout under the same name again

The freshly recreated approllout CR never gets a status and no new chartassignment CRs are recreated. However when you check the chartassignments CRs the old chartassignment of the offline robot is still present. This happens because the finalizer set by cr-syncer is still present and prevents deletion. This seems to block the creation of new chartassignments for the same approllout.

A workaround is removing the finalizer from orphaned chartassigment CR manually.

**Comment by drigz** [comment]
First thoughts: probably the easiest fix would be to allow the approllout controller to patch existing chartassignments when handling a new approllout. However, that might be inconvenient if you're intentionally using delete-recreate to trigger recreation of the chartassignments to work around a bug somewhere.

It would be nice to fix the "deleting CR that's been synced to a turned-off robot" case, as it's generally quite annoying, although significantly more work. I can imagine replacing the current finalizer-based approach with a GC-based approach, where synced CRs have references to the UIDs of the original CR.

**Comment by oliver-goetz** [comment]
Your second idea sounds very good, because the "deleting CR that's been synced to a turned-off robot" case appears to be the root cause and generates more effort for fixing.
Patching the CRs could cause other issues. Sometimes I delete and recreate an approllout to ensure that a pod is running with the latest version of a docker image. In the Patching cause I could not be sure about this without checking the chartassigments explicitly, because I might recreate the approllout too fast before the chartassigment was deleted.
