### ISSUE TITLE
1h token lifetime leads to bad usabillity for human operators

### ISSUE THREAD

**Issue by ensonic** [googlecloudrobotics/core#52]
In 556fba251f40137c6f7caab493e537aa8638aab0 the 'cookie-expire' flag for the oauth2-proxy was set to 1h to match the lifetime for bearer tokens as produced by the token vendor for robots (see https://github.com/googlecloudrobotics/core/pull/40).
Now this has the side effect that also web session for users expire after one hour, which is especially bad when watching a grafana dashboard and have the refresh enabled.

Now sure if there is a way to split the flow to be able to have separate settings depending on the key type.

**Comment by drigz** [comment]
Update: oauth2-proxy's `--cookie-refresh` flag seems like it should help with this, but https://github.com/oauth2-proxy/oauth2-proxy/issues/793 means that it doesn't work properly.

**Comment by ensonic** [comment]
the nginx-ingress support auth caching which we probably need (we run v0.44.0 which is recent enough). It seem that the issue comes from parallel request to the refresh and those leading to invalidating the cookie. Trying it now.

**Comment by ensonic** [comment]
WIP patch: https://gist.github.com/ensonic/29ef5d938b5b008dfcd70bf99139a8f1

Upgrading oauth2-proxy after
https://github.com/oauth2-proxy/oauth2-proxy/pull/1063
has been merge will be useful too (e.g. if you leave a grfana dashboard running, it nukes the cokkie eventially and then you need to relad the page to restart the polls using the refreshed cookie).
