### ISSUE TITLE
Cloud Robotics Core failing on Bazel CI due to "gomodules.xyz/jsonpatch" change

### ISSUE THREAD

**Issue by meteorcloudy** [googlecloudrobotics/core#53]
https://buildkite.com/bazel/cloud-robotics-core/builds/3782#03762913-064b-414d-9df1-a794ec16bd6e
```
(00:27:10) ERROR: An error occurred during the fetch of repository 'xyz_gomodules_jsonpatch':
   Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_gazelle/internal/go_repository.bzl", line 126, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch xyz_gomodules_jsonpatch: fetch_repo: unrecognized import path "gomodules.xyz/jsonpatch"
(00:27:10) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_k8s_sigs_controller_runtime/pkg/webhook/admission/BUILD.bazel:3:11: @io_k8s_sigs_controller_runtime//pkg/webhook/admission:go_default_library depends on @xyz_gomodules_jsonpatch//v2:go_default_library in repository @xyz_gomodules_jsonpatch which failed to fetch. no such package '@xyz_gomodules_jsonpatch//v2': failed to fetch xyz_gomodules_jsonpatch: fetch_repo: unrecognized import path "gomodules.xyz/jsonpatch"
```

It looks like the required module is no longer there?

**Comment by ensonic** [comment]
Isn't the rootcause further up:
(00:26:48) WARNING: Download from https://mirror.bazel.build/github.com/google/protobuf/archive/v3.11.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Comment by meteorcloudy** [comment]
That's not the reason of this failure, you can see the same warning message in a successful build:
https://buildkite.com/bazel/cloud-robotics-core/builds/3781#14c44f5c-a7e1-46fd-b0e5-e67e33e90c8b
It won't be a problem because if the artifact is not actually on bazel-mirror then the original path will be used.

**Comment by meteorcloudy** [comment]
jsonpatch doesn't seem to exist at https://gomodules.xyz/, did it get renamed to jsonpatch-gen?

**Comment by faximan** [comment]
Yun, you are right that this is the problem.
https://github.com/googlecloudrobotics/core/commit/fbde792f8fa1386e1138c4bc1ef67af2344c0dbb
should be the fix.

Let us know if you run into any issues.

**Comment by meteorcloudy** [comment]
Thanks for the fix!

**Comment by meteorcloudy** [comment]
It's green on Bazel CI again: https://buildkite.com/bazel/cloud-robotics-core/builds/3784
