### ISSUE TITLE
Run setup for existing robot again deletes custom robot labels

### ISSUE THREAD

**Issue by oliver-goetz** [googlecloudrobotics/core#56]
With [this commit](https://github.com/googlecloudrobotics/core/commit/29aa7ac76e846087ef25cb724d941e70c99fdbb0) custom robot labels are deleted when you run setup_robot.sh script for existing robots.
It would be nicer if it overwrites cloudrobotics.com/* labels only.

**Comment by faximan** [comment]
Hi Oliver, that commit should solve this issue. We decided to take a slightly different approach to the one you suggested. Let us know if you run into issues!

**Comment by oliver-goetz** [comment]
Looks good! Thank you for helping so fast 😄
