### ISSUE TITLE
robot-master pod does not start because of error in helm init container

### ISSUE THREAD

**Issue by oliver-goetz** [googlecloudrobotics/core#60]
Currently the helm init container of robot-master fails with an error and prevents the start of the pod.

```
Creating /home/nonroot/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
Error from server (BadRequest): container "robot-master" in pod "robot-master-6858cdddd6-sdsbs" is waiting to start: PodInitializing
```
The reason seems to be the invalid kubernetes-charts.storage.googleapis.com Helm repository, as already pointed out in Stefans commit 279ebb3 This seems to be the default stable repo of Helm v2.13 release, we currently used.

**Comment by oliver-goetz** [comment]
Btw. this affects all current robot-masters. Whenever a new pod needs to be created, it won't come up.

**Comment by ensonic** [comment]
PR #61 is the fix, right? Can we close this or is there anything else that needs to be done?

**Comment by oliver-goetz** [comment]
Yes it is. I documented it here in case someone is wondering, why robot-master is not working anymore.
It can be closed now.
