### ISSUE TITLE
Get all tests passing with --incompatible_disable_legacy_cc_provider for Bazel 0.25.0

### ISSUE THREAD

**Issue by oquenchil** [googlecloudrobotics/core#7]
It seems that Cloud Robotics Core will start breaking with the next Bazel release 0.25 because of an incompatible change (https://github.com/bazelbuild/bazel/issues/7036)

`ERROR: /home/bazel/.cache/bazel/_bazel_bazel/c6d20798bfe5b1f78a6158f10ba87246/external/org_golang_x_sys/unix/BUILD.bazel:3:1: in libs attribute of _cgo_collect_info rule @org_golang_x_sys//unix:go_default_library%windows_386%cgo_info: '@org_golang_x_sys//unix:go_default_library%windows_386%cgo_c_lib' does not have mandatory providers: 'cc'. Since this rule was created by the macro 'go_library_macro', the error might have been caused by the macro implementation in /home/bazel/.cache/bazel/_bazel_bazel/c6d20798bfe5b1f78a6158f10ba87246/external/io_bazel_rules_go/go/private/rules/cgo.bzl:694:16`

I don't see any errors for rules_go, so it could be that Cloud Robotics Core is using an old version of rules_go?

**Comment by drigz** [comment]
I think this was fixed by https://github.com/googlecloudrobotics/core/commit/c103df875511ed9d79d713b35a12bef695788f94. I guess this was reported by a Buildkite run; do you know which version it used?

**Comment by oquenchil** [comment]
Yes, it doesn't show up anymore. It must have been right before that update. Thank you Rodrigo!
