### ISSUE TITLE
ROS2 communcation between cloud robotics core and robot cluster

### ISSUE THREAD

**Issue by swgu931** [googlecloudrobotics/core#73]
Hi! there,

I did setup properly both robot cluser and cloud robotics core in GKE in order to use freely ros2 communication between crc and robot-cluster. (there will be many ros2 service and pub/sub message), which means one ros2 node in crc publishing/subscribing whereas another ros2 node in robot-cluster subscribing/publishing they are working fine.

ROS2 communication is on top of UDP as Iong as I know.
Is there any way to find out solution to solve that kind problem based on kubernetes tech. or engineering ?
Generally, there was no solution, but crc and robot-cluser look like it was already authenticated each other and again identify each other before communication. 

Regarding this, anybody help me to look for a kind of solution.

Thanks in advance.
Sean

**Comment by drigz** [comment]
Hey Sean, I'm afraid this is a bit of a "won't fix" on our side: we did prototype various methods of ROS1 robot<->cloud communication (VPN and bridges based on cloud pub/sub or a custom message broker) but found that it wasn't very reliable: connectivity dropouts lead to lost messages, which breaks the assumptions of ROS nodes that assume a reliable local network.

We'd recommend a [declarative API](https://googlecloudrobotics.github.io/core/how-to/creating-declarative-api.html) or [gRPC service](https://googlecloudrobotics.github.io/core/how-to/deploying-grpc-service.html) for robot<->cloud communication, and using custom code to translate between ROS2 and the robot<->cloud API. Alternatively, you can connect your robots to a VPN: this might be easiest, but we didn't pursue it as it is not ideal from a security perspective.

**Comment by swgu931** [comment]
Many thank, Rodrigo Queiro,

I understood, and I will find other way for that.

Thank you.
