### ISSUE TITLE
 question and issue about the section "Creating a declarative API"

### ISSUE THREAD

**Issue by swgu931** [googlecloudrobotics/core#76]
Dear all for this project,

Question and issue is :

I am working on "Deploying the declarative API in the cloud" in part of the section ["Creating a declarative API"](https://googlecloudrobotics.github.io/core/how-to/creating-declarative-api.html)
finding there was no following code existing in paragraph "Deploying the declarative API in the robot".
therefore I wonder if the following code application for the cloud.

```
kubectl create namespace metacontroller
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/metacontroller/master/manifests/metacontroller-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/metacontroller/master/manifests/metacontroller.yaml
```

actually, I have the issue which metacontroller namespace in cloud cluster cannot be seen, I am doubtful of the effect of the missing step.

beside of that, I went through "Deploying the declarative API on the robot" which looks OK.
I had not much knowledge of metacontroller so I will repeat declarative API tests again after studying more it.

Anther small thing I want to fix is :
The metacontroller related link is wrong (site not found) in the part of the section "Creating a declarative API" 
there are two points in total by my calculating : Installing metacontroller & Deploying the declarative API in the cloud

Thanks and regards
Sean

**Comment by ensonic** [comment]
A lot of things with the metacontroller changed. I'll take a stab at updating the tutorial (including the links).

**Comment by swgu931** [comment]
First question in upper side is still open for us. So i open again.
Question is 
'''
actually, I have the issue which metacontroller namespace in cloud cluster cannot be seen, I am doubtful of the effect of the missing step.
'''

**Comment by ensonic** [comment]
Which way did you install metacontroller to the cloud:
https://metacontroller.github.io/metacontroller/guide/install.html

If in double you can follow the same instruction as for installing it on the robot. Make sure the cloud gke cluster is your default context and then run:
```
kubectl create namespace metacontroller
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller-crds-v1.yaml
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller.yaml
```
