### ISSUE TITLE
can not access "cloud-robotics-discuss@googlegroups.com".

### ISSUE THREAD

**Issue by fukuta-tatsuya-intec** [googlecloudrobotics/core#8]
It is as the title.
Please tell me how to communicate with your project.

**Comment by ensonic** [comment]
Hi Tatsuya, for technical discussion the github issues can be the right forum. For general discussion you can use the discussion group, we just lifted some restriction a little further. You still need to join the group to be able to post though. Is this okay for you?

**Comment by fudekun** [comment]
Thank you for ensonic response.
Of course. I'm convinced that GitHub's issue is a place for technical discussions.
However, I wanted to discuss the connect between Google Cloud Robotics and our OSS project for ROS robots using K8s(https://github.com/rdbox-intec/rdbox). Therefore I wanted to ask about "Layer 2: App Management". The figure "https://github.com/googlecloudrobotics/core/blob/master/docs/overview.md" has the description "On-Premise", whose source code doesn't exist yet.

But
I think that argument is not appropriate for GitHub's issue.

Where is the appropriate contact available to me?

**Comment by ensonic** [comment]
Thaks for the details. Could you retry to start a discussion thread on cloud-robotics-discuss@googlegroups.com?

**Comment by fukuta-tatsuya-intec** [comment]
I'm sorry.
I can not find "cloud-robotics-discuss@googlegroups.com". Need my Google Account Information?

**Comment by ensonic** [comment]
You can sign up here: https://groups.google.com/forum/?pli=1#!forum/cloud-robotics-discuss

**Comment by fukuta-tatsuya-intec** [comment]
I succeeded in joining GoogleGroups.
thank you very much.
