### ISSUE TITLE
Problems with the Quickstart

### ISSUE THREAD

**Issue by JS2103** [googlecloudrobotics/core#88]
Hello,
I'm currently trying to deploy my project via the Quickstart Guide in the documentary. Everything seems to work fine until I try to run the install script in the 4. and last step.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/98394629/150969452-b534a181-93c5-402e-bf73-911433d18ff4.png">
I already set a new default region/zone (via gcloud compute project-info add-metadata \
    --metadata google-compute-default-region=europe-west1,google-compute-default-zone=europe-west1-c)
 but the ERROR remains.
Did anyone else had this problem and was able to solve it?

Greetings,
Jan

**Comment by ensonic** [comment]
If you:
```
gsutil cat gs://<your-gcp-project>-cloud-robotics-config/config.sh
```
does this have GCP_ZONE set? Otherwise try:
```
bash ./run-install --set-config
```
through which you can interactively set the zone into the config.

**Comment by drigz** [comment]
The problem appears to be that run-install.sh doesn't work in Cloud Shell. It works for me locally, but in Cloud Shell, the output when listing zones looks different:

```
local$ gcloud compute zones list -q --project $PROJECT_ID
...
us-west4-c                 us-west4                 UP

cloudshell$ gcloud compute zones list -q --project $PROJECT_ID
NAME: us-west4-c
REGION: us-west4
STATUS: UP
NEXT_MAINTENANCE:
TURNDOWN_DATE:
```

I can't work out why this is (even `gcloud compute zones list --help` says "in table form") but I think we can make this less fragile.

**Comment by drigz** [comment]
FYI, it will take a day or so before the fix is present in a release that `run-install.sh` can see. When I tried with Cloud Shell I also needed to run `sudo apt install google-cloud-sdk-gke-gcloud-auth-plugin`, I'm updating the instructions to reflect this.

**Comment by JS2103** [comment]
Thanks a lot

**Comment by drigz** [comment]
@JS2103 Please try again and let us know if the problem is not resolved.

**Comment by JS2103** [comment]
It seems to work completely fine now! Thanks again!
