### ISSUE TITLE
Build breakage with upcoming Bazel change for Python toolchains

### ISSUE THREAD

**Issue by brandjon** [googlecloudrobotics/core#9]
This project [fails to build](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/104#67048d05-5d9b-4141-ac03-5ea16b32a987/3543-3689) when [`--incompatible_use_python_toolchains`](https://github.com/bazelbuild/bazel/issues/7899) is enabled. It looks like you have a Python 2 target used as a tool in the host configuration, but the host configuration by default uses Python 3. We don't support multiple Python versions in the host configuration, but you can choose which version is used build-wide by setting `--host_force_python=PY2`. See the migration bug and bazelbuild/bazel#6443 for details.

**Comment by davschm** [comment]
Thanks for making us aware of this. We have temporarily fixed it with `--host_force_python=PY2` in
https://github.com/googlecloudrobotics/core/commit/e028093a77e038f632624c9f3d2c80b559653bf6.

The problem seems to be that `pip_import` and `pip_install` still download Python-2-compatible wheels of the dependencies even though the host configuration uses Python 3. Do you have any suggestion what to do about this?

**Comment by brandjon** [comment]
This will have to be fixed in `rules_python`. I can look into that after this toolchain flag flip is in. In the meantime `--host_force_python` is the way to go if you have PY2-only targets built in the host configuration.

I'm reopening this because this project is still [failing in our downstream CI](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1008#4ff95ac7-b2ae-4b3b-8cf0-0cd65b0a7d2c). Looking at one of the failures, I see [here](https://github.com/googlecloudrobotics/core/blob/f6e864f57d040635e824b157c185fb51d971511c/bazel/build_rules/ros/ros_py_test/BUILD.bazel) that the `python_version` attribute is not set (in the `py_test` created by `ros_py_test`). The default is PY3, so you may need to add `python_version = "PY2"` to the macro (or pass it in as a macro parameter if the required version differs between call sites).

**Comment by brandjon** [comment]
Er, I'm *not* reopening this because I forgot I'm posting in a repo I don't have commit rights to. Leaving that to you. =)

**Comment by drigz** [comment]
Thanks for the pointer, will look into why the previous commit didn't fix it!

**Comment by brandjon** [comment]
Confirmed fixed in [most recent CI run](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1014#af26a583-1049-494b-badd-41e0e21b410a). Thanks!
