### ISSUE TITLE
Cloud Robotics Core fails to build with mainline Bazel

### ISSUE THREAD

**Issue by Wyverald** [googlecloudrobotics/core#90]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2547#0181f780-2db2-4833-a314-2aa5ef17498a

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-x60h/bazel-downstream-projects/core/src/bootstrap/cloud/BUILD.bazel:51:8: //src/bootstrap/cloud:crc-binary: no such attribute 'deps' in '_real_pkg_tar' rule
```

See https://github.com/bazelbuild/bazel/issues/14797 for more information (basically, the version of `pkg_tar` bundled with Bazel is deprecated; you should use https://github.com/bazelbuild/rules_pkg instead.

**Comment by Wyverald** [comment]
See also the change in Bazel that removed the `deps` attribute: https://github.com/bazelbuild/bazel/commit/52bca194c61d6c60402c4af19b64d1d65ecf4ca8

**Comment by ensonic** [comment]
We only used 'deps' in https://github.com/googlecloudrobotics/core/blob/master/src/bootstrap/cloud/BUILD.bazel#L51. We can probably use file_groups in the other pkg_tar rules and then put the file_groups into srcs, right?

**Comment by Wyverald** [comment]
I'm not too familiar with the usage of pkg_tar, sorry :/ @aiuto would know.

**Comment by aiuto** [comment]
You should migrate to rules_pkg.  https://github.com/bazelbuild/rules_pkg/releases/tag/0.7.0

And in https://github.com/googlecloudrobotics/core/blob/master/src/bootstrap/cloud/BUILD.bazel#L1 load from 
@rules_pkg://pkg:tar.bzl

The will get you a drop-in replacement that will work with what you have. You could, though, restructure the rules to use pkg_files to remap the individual parts. That would be clearer and quicker to evaluate than building 5 tarballs just to untar therm and retar them into the final package.

**Comment by meteorcloudy** [comment]
This is the only remaining project to be fixed in bazel downstream, if this cannot be fixed in time, we should disable the project temporarily to get a green downstream.

**Comment by aiuto** [comment]
It looks like the Bazel team ends up doing the bulk of the PRs agains this repo.
Does anyone actively maintain it? 
Should this be in a release blocking CI if it does not have active support?

**Comment by ensonic** [comment]
The project is actively maintained. I can fix this if no one beats me with
a PR until maybe the end of next week. I am currently travelling and have a
lot of workshops.

**Comment by ensonic** [comment]
I don't see whats wrong right now:

```
bazel test //...
ERROR: error loading package 'src/bootstrap/cloud': Label '@rules_pkg//pkg:tar.bzl' is invalid because 'pkg' is not a package; perhaps you meant to put the colon here: '@rules_pkg//:pkg/tar.bzl'?
```
when I make that change:
```
> bazel test //...
ERROR: error loading package 'src/bootstrap/cloud': cannot load '@rules_pkg//:pkg/tar.bzl': no such file
```

```
> bazel version
Build label: 5.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:02:26 2022 (1654617746)
Build timestamp: 1654617746
Build timestamp as int: 1654617746
```

```
> curl -sL https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.7.0/rules_pkg-0.7.0.tar.gz | tar tvzf - | grep "tar.bzl"
 r--r--r-- 0/0           12449 2000-01-01 01:00 ./pkg/private/tar/tar.bzl
-r--r--r-- 0/0             708 2000-01-01 01:00 ./pkg/tar.bzl
```

but:
```
> find $(bazel info output_base)/external/rules_pkg -name "*.bzl" -printf "%f\n"path.bzl
deps.bzl
version.bzl
rpm.bzl
rpm.bzl
pkg_filegroup.bzl
pkg.bzl
defs.bzl
```

why do I get a crippled copy under external?

**Comment by ensonic** [comment]
Okay, randomly moving it around in the WORKSPACE file fixed it.

**Comment by aiuto** [comment]
My hunch is that you also have rules_docker, but rules_docker is depending on a very old rules_pkg. So if rules_docker was in the workspace first you were getting the older rules_pkg in external.
