### ISSUE TITLE
error: unable to recognize "charge-action.yaml"

### ISSUE THREAD

**Issue by jasirjasir** [googlecloudrobotics/core#92]
I am getting the error `error: unable to recognize "charge-action.yaml": no matches for kind "ChargeAction" in version "example.com/v1"` while running the script charge-action.yaml. My Controller is running on the cloud and action is running from robot. 

> apiVersion: example.com/v1
kind: ChargeAction
metadata:
  name: my-charge-action
  
  Did anyone faced similar issue?

**Comment by drigz** [comment]
Did you run the following command on the robot?

```
kubectl apply -f https://raw.githubusercontent.com/googlecloudrobotics/core/master/docs/how-to/examples/charge-service/charge-crd.yaml
```

This is part of [Deploying the declarative API on the robot](https://googlecloudrobotics.github.io/core/how-to/creating-declarative-api.html#deploying-the-declarative-api-on-the-robot).

**Comment by jasirjasir** [comment]
@drigz , Actually my charge controller is running on cloud and charge action on robot. In that case,  the command you shared is suppose to be run on cluster not on robot .I guess, we have to run only charge-action.yaml on the robot. Please correct me if I am wrong.

Even I tried setting up cluster and robot in reverse way, Everything except charge-action.yaml is working fine. I don't know what i am doing wrong .Anyone actually tried this [example ](https://googlecloudrobotics.github.io/core/how-to/creating-declarative-api.html#deploying-the-declarative-api-on-the-robot) completely? If so, please share the expected output. I am stuck with this issue for 1 week

**Comment by drigz** [comment]
Thanks for following up. It looks like the tutorial flow got broken when we switched to the newer CRD version: someone accidentally switched `charge-crd.yaml` to v1alpha1, but `charge-action.yaml` still refers to v1.

I'll let you know when a fix is submitted. Until then, you can try creating charge-action.yaml with the following contents:

```
apiVersion: example.com/v1alpha1
kind: ChargeAction
metadata:
  name: my-charge-action
```

**Comment by drigz** [comment]
I've updated the CRD. If you already installed the old CRD, you'll need to delete it with:

```
kubectl delete customresourcedefinition.apiextensions.k8s.io/chargeactions.example.com
kubectl apply -f https://raw.githubusercontent.com/googlecloudrobotics/core/master/docs/how-to/examples/charge-service/charge-crd.yaml
```

After this, you should be able to apply the normal ChargeAction from the instructions. Let me know if you encounter trouble.

**Comment by jasirjasir** [comment]
Thanks for the reply, but still the issue exist. Getting the following error  when running `kubectl apply -f charge-action.yaml   && watch -n0 kubectl describe chargeaction my-charge-action` from cloud(workstation)

> error: resource mapping not found for name: "my-charge-action" namespace: "" from "charge-action.yaml": no matches for kind "ChargeAction" in version "example.com/v1"

My setup is like this
  **charge -crd and charge-controller   -  On Robot
  charge-action  - On cloud** 
  
  Is there any mistake I am doing ? Not able to figure out the issue.

**Comment by drigz** [comment]
You need to apply charge-crd.yaml to both clusters. It appears twice in the documentation because in both clusters, a CustomResourceDefinition (from charge-crd.yaml) must be created before the ChargeAction custom resource can be created.

**Comment by jasirjasir** [comment]
@drigz , made a ittle progress. Currently, I am able to run all the files required for running charge action 

Setup : 
**charge-crd.yaml,charge-controller.yaml - on Robot
charge-crd.yaml, charge-action.yaml  - on Cloud**

After running the command  `kubectl apply -f charge-action.yaml   && watch -n0 kubectl describe chargeaction my-charge-action` from cloud shell, getting the following screen.

![image](https://user-images.githubusercontent.com/38342952/181007251-9f966974-b104-4b09-9160-b0b5d63b457d.png)

Instead of workstation, I am running everything from a cloud shell. Hope that won't make any difference. I have two doubts here
1)I couldn't see any places where charge-level percentage are getting incremented(even charge state as well).Is there any mistake in my setup?
2)Even if I see the status update, how can I access it programmatically instead of viewing from terminal.

**Comment by drigz** [comment]
> Actually my charge controller is running on cloud and charge action on robot.

You might have caused problems by not following the instructions directly. I would suggest following the instructions directly at first, and then changing one thing at a time so that you know what affects the behavior.

When you know exactly what change is causing the problem, please post the details of how you've diverged. It's possible that you've moved the controller but haven't changed the `cr-syncer.cloudrobotics.com/spec-source` setting (docs: https://googlecloudrobotics.github.io/core/concepts/federation.html#cr-syncer) but it's also possible that the cr-syncer or controller is not deployed or operating correctly.
