### ISSUE TITLE
How to access robot from cloud via REST API

### ISSUE THREAD

**Issue by jasirjasir** [googlecloudrobotics/core#93]
I have set up my GCP cloud and robot based on the tutorials provided by cloud robotics team. I am able to send and receive data between robot and cloud using pubsub. Also, i have set up a nginx server on cloud and able to access the services from robot. I have another requirement to access robot from cloud for applications such as GET current robot details, assign task to robot etc. Can someone suggest the best approach for implementing this? I need to establish a synchronous communication between cloud and robot in such a way that cloud will request data and robot has to return the response.

**Comment by drigz** [comment]
Beyond the custom resource approach described in the ChargeAction tutorial, Cloud Robotics doesn't offer additional support for cloud/robot API support. I'm aware of some other approaches (eg https://github.com/rancher/remotedialer, https://openvpn.net/) but the right choice is specific to the design of your setup so I'm afraid we can't support it directly.
