### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break Cloud Robotics Core in a future Bazel release

### ISSUE THREAD

**Issue by keertk** [googlecloudrobotics/core#94]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in a future Bazel release [1], thus breaking Cloud Robotics Core.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-2f3a-470e-99fb-9eb2f84351c7)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

[1] The target release hasn't been determined yet. Our tool will update the issue title once the flag flip has been scheduled.

**Comment by ensonic** [comment]
```
bazel build --incompatible_config_setting_private_default_visibility //...
INFO: Analyzed 335 targets (1363 packages loaded, 23933 targets configured).
INFO: Found 335 targets...
INFO: Elapsed time: 52.304s, Critical Path: 38.31s
INFO: 41 processes: 1 internal, 40 linux-sandbox.
INFO: Build completed successfully, 41 total actions
```

**Comment by ensonic** [comment]
Still fails du to another rule-package
```
(01:13:08) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8f64c2da58aba524c96e00bc4efb6144/external/io_bazel_rules_go/BUILD.bazel:106:10: in go_config rule @io_bazel_rules_go//:go_config: target '@io_bazel_rules_go//go/private:stamp' is not visible from target '@io_bazel_rules_go//:go_config'. Check the visibility declaration of the former target if you think the dependency is legitimate
--
  | (01:13:08) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8f64c2da58aba524c96e00bc4efb6144/external/io_bazel_rules_go/BUILD.bazel:106:10: Analysis of target '@io_bazel_rules_go//:go_config' failed
  | (01:13:08) ERROR: Analysis of target '//src/go/pkg/synk:go_default_test' failed; build aborted:


```
