### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Cloud Robotics Core in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [googlecloudrobotics/core#95]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking Cloud Robotics Core. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-16f3-4eea-ab74-d8480e1a0d15)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi @ensonic, Could you please look into this issue and share any significant update. Thanks!

**Comment by ensonic** [comment]
We're trying to port from rules_docker to rules_oci (see #130), but have trouble finding a good replacement for:
```
load("@io_bazel_rules_docker//container:providers.bzl", "ImageInfo", "ImportInfo")
```
see https://github.com/googlecloudrobotics/core/blob/main/bazel/app_chart.bzl#L1

Any ideas?

**Comment by drigz** [comment]
I had a look at rules_oci and found that it reads the digest from a file `index.json`: https://github.com/bazel-contrib/rules_oci/blob/d79412e7aadbb835f8e15819c6f67323d430430d/oci/private/push.sh.tpl#L40

Is that file generated for the images in https://github.com/googlecloudrobotics/core/pull/163? Can we adapt our rules to read the digest from index.json?

**Comment by ensonic** [comment]
The only pending migration:
```
Migration is needed for the following flags:
--
  | --incompatible_disable_starlark_host_transitions

```
